### ISSUE TITLE
TSlint complains about .vue extension

### ISSUE THREAD

**Issue by cr0cK** [prograhammer/vscode-tslint-vue#1]
Hi,

Thanks you for the extension. I'm looking since several days the best way to lint my typescript code into SFC files and I hope that your extension or Vetur will do the job.

I installed it and try to format a .vue file and tryed to format a vue file. But I've got a traceback:

```
[Info  - 12:53:47] Linter is running.
[Info  - 12:53:48] TSLint library loaded from: /home/alexis/workspace/vue-project/node_modules/tslint/lib/index.js
[Info  - 12:53:48] vscode-tslint: '
Invalid source file: /home/alexis/workspace/vue-project/src/pages/samples/forms/index.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                ' while validating: /home/alexis/workspace/vue-project/src/pages/samples/forms/index.vue stacktrace: FatalError: 
Invalid source file: /home/alexis/workspace/vue-project/src/pages/samples/forms/index.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                
    at new FatalError (/home/alexis/workspace/vue-project/node_modules/tslint/lib/error.js:27:28)
    at Linter.getSourceFile (/home/alexis/workspace/vue-project/node_modules/tslint/lib/linter.js:202:23)
    at Linter.lint (/home/alexis/workspace/vue-project/node_modules/tslint/lib/linter.js:72:31)
    at /home/alexis/.vscode/extensions/prograhammer.tslint-vue-1.1.0/server/server.js:426:24
    at Generator.next (<anonymous>)
    at fulfilled (/home/alexis/.vscode/extensions/prograhammer.tslint-vue-1.1.0/server/server.js:7:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

We can see that it's the server.js of the extension that is called, but my global TSlint version (5.8.0) complains about the file extension. And I don't really want to tweak TSLint itself.

Do I miss something?

**Comment by prograhammer** [comment]
Where is your `tsconfig.json` located? You shouldn't be getting an error like this.

**Comment by cr0cK** [comment]
`tsconfig.json` is at the root of the project. And the index.vue is a dummy SFC:

```
<script lang="ts">
import Vue from 'vue'

console.log('tslint should complains about this line and its not the case');

export default Vue.extend({
  data: function() {
    return {
      foo: 'bar'
    }
  },
})
</script>

<template>
  <div>
    {{ foo }}
  </div>
</template>
```

**Comment by prograhammer** [comment]
I tried with a `.vue` file with those contents it works correctly. Can you try using a local TSLint (5.8.0+)? `npm install tslint`.

**Comment by prograhammer** [comment]
Let's try something a bit hacky. Go to `/home/alexis/.vscode/extensions/prograhammer.tslint-vue-1.1.0/server/server.js` and update line #478 so that it has a `console.log` below it like this:

```
    host.resolveModuleNames = function (moduleNames, containingFile) {
        console.log('File contents here: ' + updatedContents);
```

Make sure you have `"tslint.typeCheck": true` in your VSCode settings.json file so the typechecker level of linting is turned on and the `console.log` gets hit. Now restart VSCode and go to a `.vue` file in VSCode editor. What does the `output` tab show (for tslint)? You should see the contents of your `.vue` file (with some added `// ` comment lines for padding to preserve line numbers).

**Comment by prograhammer** [comment]
Oh, and you don't have vscode-tslint extension installed do you? If you need to uninstall that one and just use vscode-tslint-vue (this extension) by itself.

**Comment by cr0cK** [comment]
So, i see the output like expected, I have uninstalled vscode-tslint but I sill have the error about the not supported extension in the tslint output:

```
File contents here: //
import Vue from 'vue'

console.log('tslint should complains about this line and its not the case');

export default Vue.extend({
  data: function() {
    return {
      foo: 'bar'
    }
  },
})

[Info  - 14:21:18] vscode-tslint: '
Invalid source file: /home/alexis/workspace/vue/vue-project/src/pages/samples/forms/index.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                ' while validating: /home/alexis/workspace/vue/vue-project/src/pages/samples/forms/index.vue stacktrace: FatalError: 
Invalid source file: /home/alexis/workspace/vue/vue-project/src/pages/samples/forms/index.vue. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.
                
    at new FatalError (/home/alexis/workspace/vue/vue-project/node_modules/tslint/lib/error.js:27:28)
    at Linter.getSourceFile (/home/alexis/workspace/vue/vue-project/node_modules/tslint/lib/linter.js:202:23)
    at Linter.lint (/home/alexis/workspace/vue/vue-project/node_modules/tslint/lib/linter.js:72:31)
    at /home/alexis/.vscode/extensions/prograhammer.tslint-vue-1.1.0/server/server.js:426:24
    at Generator.next (<anonymous>)
    at fulfilled (/home/alexis/.vscode/extensions/prograhammer.tslint-vue-1.1.0/server/server.js:7:58)
    at <anonymous>
```

**Comment by cr0cK** [comment]
And I confirm that I'm using a local install of TSlint like the output said:

`[Info  - 14:28:16] TSLint library loaded from: /home/alexis/workspace/vue/vue-project/node_modules/tslint/lib/index.js`

**Comment by prograhammer** [comment]
Ok, I'm seeing the problem. It looks like it all works as long as there is an import from your `main.ts` file or in a file in the chain leading back up to that file. And it looks like you have to reference the full path:

```
// main.ts (entry)
import Vue from 'vue'
import App from 'import test from/home/alexis/workspace/vue/vue-project/src/pages/samples/forms/index.vue`

// ...

```
I'm trying to fix this now...

**Comment by cr0cK** [comment]
Ok thank you :)

FYI, maybe it's related, I see this in the tsc.js file:

```
function extensionIsOk(extensions, extension) {
        switch (extensions) {
            case Extensions.JavaScript:
                return extension === ".js" || extension === ".jsx";
            case Extensions.TypeScript:
                return extension === ".ts" || extension === ".tsx" || extension === ".d.ts";
            case Extensions.DtsOnly:
                return extension === ".d.ts";
        }
    }
```

But even if I console.log into it, I never see my logs...

**Comment by prograhammer** [comment]
Ok, that **big bug is fixed**! The problem was that the typechecker wasn't picking up on relative paths for `.vue` files (and I didn't notice I had changed all my import statements to absolute paths during a test). 

Also, it appears the typechecker level of linting will only work on a `.vue` file that is found somewhere on the dependency chain that eventually leads up to your entry file (`main.ts`). So the `.vue` has to imported in some nested file that has an ancestor that your main entry file references (that's where the compiler starts to look for modules and walks through the files to gather further dependencies). Does that make sense? I'm looking into how to work around this but it may be that TypeScript won't let us.

**Comment by prograhammer** [comment]
Let me know if it's working for you @cr0cK and we can close this issue. Thanks so much for reporting this.

**Comment by cr0cK** [comment]
No sorry, I still have the same error.

I'm using nuxt so i'm not sure about the direct dependency that your describe. I've setup a full nuxt empty project for easier debugging.

https://github.com/cr0cK/vscode-tslint-vue-issue1-example

You can checkout and try if you have errors in the `pages/index.vue` file.

Thanks :)

**Comment by prograhammer** [comment]
@cr0cK I've done a lot of thinking and I've come to the conclusion that the best route for Vue + TypeScript developers is to start using `.vue.ts` extension. To rename all `.vue` to `.vue.ts`. Then, if you have Vetur installed, just update your `settings.json` with your new file association:

```json
    "files.associations": {
        "*.vue.ts": "vue"
    },
```
TypeScript is too much married to the `.ts` extension. Lots of tools/packages and so on make this assumption and for several reasons (especially maintenance) I think this is the best way to go. The TSLint Vue package in it's current version will work with `.vue.ts` as well (as long as you tell VSCode about the association as mentioned above in your settings).

**Comment by cr0cK** [comment]
I think you're right but unfortunately, renaming vue files to vue.ts leads to another problems...

- With nuxt for example, the router is not working anymore since it doesn't found vue files
- With webpack template for vue-cli, all the content of my vue.ts files are now parsed by TypeScript instead of only the <script> part. I'm still stuck on that.

Finally, I'm wondering if the better approch is to avoid vue files and use TSX files like [here](https://github.com/Lemoncode/vuejs-by-sample/tree/master/03%20Render/src) or use TS files with vue-component-class like [here](https://github.com/ducksoupdev/vue-webpack-typescript/blob/master/template/src/components/about/about.ts). No vue-loader, only ts-loader and tslint will work since it's only some typescript.

But I'm not a huge fan of both for Vue :/

**Comment by prograhammer** [comment]
@cr0cK The reason it's not working in your Nuxt example is because your Vue component is never referenced from a `.ts` file. For example, create a file called `modules.ts` then import your test file like this: 
```js
// modules.ts
import Test from '@/pages/samples/forms/index.vue`
```
Then your index.vue will lint properly. But I still think it's better to go with `.vue.ts`. Nuxt may need to offer a way to read routes with different extensions (or let you populate an array). I'll look into the problem you have with `vue-cli` and `.vue.ts`, but I imagine you just need to tweak your test/rules for webpack there.

**Comment by cr0cK** [comment]
Yes, tslint is able to lint my vue files if I import explicitly my vue file but now, TypeScript don't compile because it can't import the vue file !

I think you're right, `.vue.ts` is certainly the way to go...

**Comment by prograhammer** [comment]
Yeah @cr0cK I'm planning to look into that later today or tomorrow. However, **I think I've almost figured out** how to get the compiler to pick up all `.vue` files (no matter if they are referenced in an import chain leading from a `.ts` file)!!!

It looks like the internal option `allowNonTsExtensions` still exists. You can see [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L3789) and used [here](https://github.com/Microsoft/TypeScript/blob/40c32136f16cec7b6c52e8bf5021bbb844a0ca14/src/compiler/program.ts#L1687).

There's just one hurdle I'm working on (TypeScript doesn't respect `tsconfig.json` for searching .vue root files). I'm digging into the sourcecode now to see how this is resolved. Right now I manually supply the `.vue` files and with `allowNonTsExtensions` set to true (from within TSLint Vue extension) I'm able to see it working on any `.vue` file.

**Comment by cr0cK** [comment]
Looks good :)

**Comment by prograhammer** [comment]
**Done! Check out v1.3.0!** 

It should lint `.vue` files in your Nuxt project. It's no longer required that they be referenced from an import in `.ts`. Let me know if it is working for you @cr0cK

**Comment by cr0cK** [comment]
Yeah! It works like a charm. Thank you.

Do you plan to do a PR to the original vscode-tslint project or continue the fork? I think it'd be better if only one extension could handle almost all libraries with maybe some configuration options to support vue files for example.

**Comment by prograhammer** [comment]
Yeah, I might try to do a PR on this extension: https://marketplace.visualstudio.com/items?itemName=eg2.ts-tslint. If the PR isn't accepted, then I'll update the code here to fork from it because it's a more optimized approach.
